GET http://localhost:3000/todos

###
GET http://localhost:3000/todos/695d2fcef17a23204c3f118d

### 
PUT http://localhost:3000/todos/695d2fcef17a23204c3f118d
Content-Type: application/json

{
  "text": "Learn about containers v2"
}

###
POST http://localhost:3000/todos/
Content-Type: application/json

{
  "text": "The task for the day #3"
}